var PLAYER_MAX_HP = 100;
//
var DEFAULT_SHOT_DAMAGE = 1;
var FIRE_SHOT_DAMAGE = 1;
var ICE_SHOT_DAMAGE = 1;
var SPREAD_SHOT_DAMAGE = 1;
var ELECTRIC_SHOT_DAMAGE = 1;
//
var FOOT_STEP_INTERVAL = 20; // In frames at 60fps
//
// Interval between shots, in seconds
var DEFAULT_SHOT_PLAYER_DELAY = 0.25;
var FIRE_SHOT_PLAYER_DELAY = 0.25;
var ICE_SHOT_PLAYER_DELAY = 0.25;
var SPREAD_SHOT_PLAYER_DELAY = 0.25;
var ELECTRIC_SHOT_PLAYER_DELAY = 3;
//
// Shot speed, in pixels per frame
var DEFAULT_SHOT_PLAYER_SPEED = 10;
var FIRE_SHOT_PLAYER_SPEED = 20;
var ICE_SHOT_PLAYER_SPEED = 10;
var SPREAD_SHOT_PLAYER_SPEED = 5;
//
var DEFAULT_SHOT_ENEMY_SPEED = 5;
var FIRE_SHOT_ENEMY_SPEED = 10;
var ICE_SHOT_ENEMY_SPEED = 5;
var SPREAD_SHOT_ENEMY_SPEED = 2;
//
var ELECTRIC_SHOT_SPEED = 40; // In pixels per frame
var ELECTRIC_SHOT_AMOUNT = 20;
var ELECTRIC_SHOT_START_DELAY = 1; // In seconds
//
var ENEMY_SPREAD_SHOTS_AMOUNT = 5;
var ENEMY_SPREAD_DEGREE_RANGE = 30;
//
var ICE_SLOW_MULTIPLIER = 1;
